name: Feature request
description: Request a feature for starcat-recommend-api
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
